### ISSUE TITLE
SWProxy unable to to pull any information

### ISSUE THREAD

**Issue by STFUppercut** [kakaroto/SWProxy#106]
I have used this program many times and I have checked the settings for everything twice, and have reset my computer and phone and tried it again.  Checked the settings a 2nd time.  Everything looks to be the same as it always has been, but now SWProxy is just being dormant while it is running.  

What stupid detail am I missing?

**Comment by STFUppercut** [comment]
While SWProxy is running Summoners War logs into the game and runs fine.

**Comment by Xzandro** [comment]
Did you test the new version from today? https://github.com/lstern/SWProxy-plugins/releases With the recent patch, com2us changed some things.

**Comment by STFUppercut** [comment]
I don't know how I missed that, everything is working again now.  Thanks for the help!
