### ISSUE TITLE
Proxy error?

### ISSUE THREAD

**Issue by libreidy** [kakaroto/SWProxy#109]
After starting  SWproxy and manually setting proxy on my iphone I am not able to connect to the internet at all.
I'm not sure what I'm doing wrong. Please help me.

I sometimes get this error also(Below)

![error](https://cloud.githubusercontent.com/assets/13302352/16100081/ec1d2208-3329-11e6-9124-739317bf4331.jpg)

**Comment by libreidy** [comment]
Got it to connect to the internet after clicking on 'allow other network users to connect through this computer's internet connection' in local area connection properties.
 Now,  if only I can get this work-around for IOS to work...

**Comment by kakaroto** [comment]
that is weird, that option shouldn't be needed at all since you're not sharing internet, you're using a proxy...

**Comment by libreidy** [comment]
Working fine with android after clicking the above option. 
Not working with IOS though, bad timing on the work-around I guess.
I'll close this thread but I hope it will help other people that has the same issue as me.
Thanks for your hard work.
