### ISSUE TITLE
This app is working?

### ISSUE THREAD

**Issue by RodrigoDLopez** [kakaroto/SWProxy#113]
Hi folk, i can connect my cellphone and get some info as you can see.
but i can't get my pack of rune.
i'm doing something wrong?
![screenshot from 2016-06-16 16-11-04](https://cloud.githubusercontent.com/assets/19981369/16130834/4c6b8a7a-33e1-11e6-97fc-921948ee589a.png)

**Comment by acenoob** [comment]
Seems like this app is down after summoners war was updated to 2.1.5

**Comment by cesium62** [comment]
I want to add the details of the symptoms I'm seeing.

I'm running the mac version of swproxy.  I'm using an android phone.

After configuring the android phone to use the http proxy, I start up summoners war.  It starts up fine.  No output appears from swproxy.  I can play the game.  When I stop swproxy, I can continue to play the game.  If I click on the 'event' icon, I get an error indicating that I can't connect to the network.  If I then modify the android phone wifi configuration to remove the proxy setting, and I then return to the game, I can click on the event icon and connect to the events http page.

So, as near as I can tell, the game is completely bypassing the proxy.

But maybe some part of the initial handshake is failing causing the game to then bypass the proxy.  If so, I'd love to get a new mac version.

**Comment by DungBui88** [comment]
yup, me too.

**Comment by msteudel** [comment]
You guys have all updated to the latest versions?

**Comment by bartolomeukuma** [comment]
i'm using 0.99.2 here.
same on linux and windows...

**Comment by Xzandro** [comment]
I think he meant this version: https://github.com/lstern/SWProxy-plugins/releases

**Comment by cesium62** [comment]
Those versions don't have a simple mac download.  But I was eventually able to get the source code to execute, and I did eventually figure out the patch to look for both qnyou and com2us in the url and I was able to get another dump of my runes and monsters.

**Comment by fuggin** [comment]
so will that help with global not working?
