### ISSUE TITLE
Swproxy isn't working since 15 days 

### ISSUE THREAD

**Issue by JFurny** [kakaroto/SWProxy#118]
Hi, when i try to take my informations from SW with Swproxy, an error message is appearing ( i'm quite bad in informatic and in english too ) : 

Traceback (most recent call last):
  File "SWParser\gui\gui.py", line 49, in openPCAP
  File "SWProxy.py", line 139, in parse_pcap
IOError: [Errno 22] invalid mode ('rb') or filename: PyQt4.QtCore.QString(u'')

Thank you if you can help me.

**Comment by Toosick** [comment]
The current release of SWProxy doesn't work but running the current source. I made a quick tutorial to run it yourself for the non tech people.

Windows tutorial

Note: I think SWProxy only works in Python 2.* so uninstall Python 3.* if you have it and you don't want to cause any problems with installation
1. Download SWProxy source, extract it somewhere: https://github.com/kakaroto/SWProxy/archive/master.zip
2. Install this: https://www.python.org/downloads/release/python-279/
3. Install this: https://www.microsoft.com/en-us/download/details.aspx?id=44266
4. Put this into your CMD prompt: cd "C:\Python27\Scripts\" && pip install yapsy pycrypto dpkt
5. Right click the SWProxy.py file that was installed in step 1
6. Open with: IDLE
7. Click F5 while in the window with code
8. Success. Should be working as normal. Your own your own from here.

**Comment by cassandraschild** [comment]
Interestingly enough, this actually worked for me.

**Comment by JFurny** [comment]
Thank you for your answer but it didn't work for me :
"Failed to load GUI dependencies. Switching to CLI mode"
Maybe i failed somewhere but i don't think so.

**Comment by cassandraschild** [comment]
I had the same message, but I continued to see if it would work after I switched to the proxy server, and after I logged in it started generating files.

**Comment by JFurny** [comment]
I tried too but when i started SW i couldn't press start it said "error something" i connected my wifi to the proxy server but it didn't work.

**Comment by cassandraschild** [comment]
No clue, but I wish you luck. So people here know, I am using windows 10-64, and a samsung device, if that info helps at all.

**Comment by JFurny** [comment]
Thank you =). I'm using windows 10 64 and a samsung device too.

**Comment by Toosick** [comment]
I got this error too but didn't try fixing it because it worked just fine. Somebody know the fix before I go fixing it?

**Comment by Toosick** [comment]
@JFurny but you got SWProxy running just fine with my steps right?

**Comment by JFurny** [comment]
Yes SWProxy was running perfectly except the error message, thank you very much for your tutorial.

**Comment by cassandraschild** [comment]
So, I tried to replicate, and I have not been able to get files since that first try. I uninstalled everything, and started the process from scratch, and still nothing. SWProxy is working, with the same error code, but no files are being generated now.

**Comment by Toosick** [comment]
@cassandraschild what error code?

**Comment by fuggin** [comment]
mine says it timed out.

**Comment by fuggin** [comment]
I as well am running windows 10-64 and a Samsung note 4.  when it does load there is no data. other wish it just keep sending the error when you press the start button. I am on global if that helps.

**Comment by FideleGastro** [comment]
Tested on windows 7 and work too

**Comment by fuggin** [comment]
Fidele what did you do? Toosick fix?

**Comment by FideleGastro** [comment]
Tested with: 
- python 2.7.9 and 2.7.11
- firewall enable/disable
- 2 emulator + phone and tablet
- pip update/no update

sorry guys, i not able to have this error and i can't test with windows 10.

This compiler require visual c++ and .net.
May try install this:
https://www.microsoft.com/en-us/download/details.aspx?id=2092
https://www.microsoft.com/fr-fr/download/details.aspx?id=49981

I dont believe, but just in case...

**Comment by cassandraschild** [comment]
"Failed to load GUI dependencies. Switching to CLI mode"
I think I figured out the issue on my end, and got it to work. I recently downloaded a VPN to deal with all the crazy lag and crashes. I thought I had turned it off, but it was turning itself back on when I logged into the game. when I made sure it would stay off, this worked.

**Comment by JFurny** [comment]
Nice ! https://github.com/lstern/SWProxy-plugins/releases
It work for me, it's the solution ! 
It's the last update for SWProxy !

**Comment by Toosick** [comment]
Oh nice he didn't want to wait for pull requests to the main SWProxy so he made his own I'm assuming.

**Comment by JFurny** [comment]
Thank you work and your help. I hope this issue will work for everybody !
