### ISSUE TITLE
decrypt ony every call

### ISSUE THREAD

**Issue by Viper2k4** [kakaroto/SWProxy#126]
Im not 100% but after a look at the code it looks liker after this:commit: https://github.com/kakaroto/SWProxy/commit/989a65a7a7cfc118b8fcbd046ab70578a5897053

Every responset would be tryed to decrypt. And with every request i mean every request. I think its not very necessary try to decrypt the request if i only brows on github.

**Comment by kakaroto** [comment]
Humm, I think you're right.. maybe @lstern can shed some light on this.

**Comment by Xzandro** [comment]
The background behind that is that a lot of people had issues, because com2us uses many different hostnames for each region, so it was an easy quick fix, I guess. And it seems to work for all people so far.

**Comment by lstern** [comment]
@Viper2k4 is correct. A patch changed the host names, we issued a quick fix then some people reported that com2us were using different hostnames per server and rather than trying to guess and evaluate all possible hostnames, I just removed the filter.

**Comment by kakaroto** [comment]
I have two conflicting opinions on this issue now : 
* we should be thorough and figure out the right hostnames... or at least, (easier and most likely) only filter out the ones with /api/gateway in the url
* People really shouldn't be using this proxy on a permanent basis, so it shouldn't matter even if it decrypts more than it should. I do know that some people use it to gather dungeon runs statistics and all that, but personally, I'd only run it once every month for about 2 minutes and disable the proxy, so I don't care that much.

**Comment by lstern** [comment]
Despite using the proxy to log all my runs, I feelthat unless someone is running this proxy on a raspberry pi the performance hit is not noticeable and I'm only 99% sure that the '/api' filter will not break the game for anyone or be future proof.

**Comment by Viper2k4** [comment]
That's the Point. I running the script on a raspberry pi (i only buy it for this job^^) to log all my runs...

- readd the Filter-Line we talk about
- add the code that i wrote here https://github.com/kakaroto/SWProxy/pull/94
- add SwarfarmLogger + config from https://github.com/lstern/SWProxy-plugins

It work just fine. I only connect my Tablet to the Proxy so i feel fine. I also plan something like a PAC-File so i could only rout the SW-API-Calls to the proxy and the rest goes through.

Simply filter out "api/gateway"-URL's sound easy to maintain. OK ok there could be same Pages outside with "api/gateway"-URL's but i think 100%-Calls agains 0,1%-Calls thats get decrypted sound like a good deal.

**Comment by kakaroto** [comment]
There are calls outside of /api/gateway, but those do not contain any of the info we're looking for anyway. I can also confirm that every API call will definitely go through that URL, only the host changes depending on the server/region/etc..

**Comment by Viper2k4** [comment]
So an easy:

    if request.url.path.startswith('/api/gateway.php'):

would be enough (the pcap-parse does somthing like this)?

**Comment by kakaroto** [comment]
Not exactly, but pretty close, I think they replaced it with gateway_v2.php, you can always look at the proxy.log file to see what the actual URL is.

**Comment by Viper2k4** [comment]
ok i have will have a lookt at it on afternoon. But if they switch to "gateway_v2.php". We should maybe use a:

    if request.url.path.startswith('/api/gateway'):

We should also have a look at the `parse_pcap` because this function still use the gateway.php.

**Comment by Viper2k4** [comment]
So the path on my client is:

summonerswar-eu.qpyou.cn:80/api/gateway_c2.php

on my client. So the IF above would work.

**Comment by Xzandro** [comment]
I dont know either. But with the "filter" some people had problems. SInce the filter is gone, no one reported problems at all.

**Comment by lstern** [comment]
the filter was more restrictive and included the hostname, /api/gateway
should be good enough

**Comment by Viper2k4** [comment]
Mh But the old filter fits also all listet servers. But ok should I create a PR?

**Comment by azrethos** [comment]
hi guys.

what is the problem with attempting to decrypt every call? inefficiency is the least of our worries

if we restrict based on certain urls we open ourselves to sniffing

plus, constructing the set of known api hosts and maintaining that list is an effort

plus, python is a "better to ask forgiveness than permission", so attempting to decrypt every request through the proxy, and silently failing, is not a problem at all

**Comment by lstern** [comment]
@azrethos while I agree with you, @Viper2k4 is trying to run swproxy on a raspberry pi

**Comment by azrethos** [comment]
then could just cache out the URLS that the decryption fails for and don't try to decrypt again for those urls

cache could just be a set() in memory of urls

**Comment by azrethos** [comment]
@lstern maybe something like this
https://github.com/kakaroto/SWProxy/pull/134

but are there any URLS (request.url.path) that will produce both fails and success decryptions? I doubt it, but this would not work in that case

**Comment by Viper2k4** [comment]
Buy why include a caching if this is not necessary. My PR dont include a filter for the Host, its only filter for the API-Calls:

https://github.com/kakaroto/SWProxy/pull/131

This fits 100% of the SW-Api-Calls and filter out 99% of the rest of the Traffic.

**Comment by azrethos** [comment]
@Viper2k4 including that as a default is a problem if they change the url, we need to issue a new release, in the cache model we wouldn't.

i'd think it would be find to add a -O or --optimize flag that would perhaps do your .startswith() check, and leave it as-is by default (because the average user will see 0 effect on efficiency, a rpi can be configured to use -O)

**Comment by Viper2k4** [comment]
Yes it simply and future proof. But on an daily use it would be an memory increase, for sure (and on bigger lists also an CPU increase^^). But doesn't matter.

I mean from me point it could be like it is. I use a very restrictive PAC-File (should only work Global,EU and JP):

```
function FindProxyForURL(url, host) {
    if (shExpMatch(host, "summonerswar*qpyou.cn"))
        return "PROXY 192.168.1.18:8080;DIRECT";

    return "DIRECT";
}
```

So on my PI the Proxy processed only SW-Calls. So im fine. But im also fine with an "-O" ^^

**Comment by kakaroto** [comment]
@azrethos I disagree, if they ever change the URL, there's a 99.999% chance that the API key will change as well so decryption would fail regardless. And the current SW release will always use the same URL path, that's a certainty, so there is no reason not to filter it like @Viper2k4 said, and we'd be safe.
There is no future-proofing something where the key can be changed at any time.

**Comment by kakaroto** [comment]
I've merged @Viper2k4's PR, so closing this issue, thanks!
