### ISSUE TITLE
Unable to update dynamic IP address from android device

### ISSUE THREAD

**Issue by GamingChica** [kakaroto/SWProxy#130]
Greetings! 

I recently setup swproxy to work with swarfarm and everything has been good. Until today. My IP address is dynamic. I went to update my settings on my phone to reflect the changed IP address but swproxy refuses to update the IP address. It will not let me manually edit the IP only the port is changeable. Is there a workaround for this? 

Thank you in advance. 

Device: Samsung Galaxy S6 Edge 6.0.1
PC: Windows 10 Pro

**Comment by Viper2k4** [comment]
Hi,

i dont rly understand. U dont have to change an IP on SWProxy. 

- start SW-Proxy on ur PC
- read the IP SWProxy show
- change the Proxy IP on Android (i the wifi settings normaly)

Nothing more todo :)

Greeting

**Comment by kakaroto** [comment]
Humm, I think @GamingChica meant that after his IP address changed, SWProxy was still listening on the previous IP or something like that... well, my suggestion is that if your IP ever changes, just close SWProxy and reopen it. There's really not much else that you can do.

**Comment by GamingChica** [comment]
Thank you for your answers. RL was a bit busy and I am late returning to this post. 

I did the above. Close, restart. I even launched the program using Run as Administrator. Nothing 'changes.' The IP address on my phone is dynamic so it changes regularly. I also, attempted to set my address to static to match that of SWProxy. That attempt led to Internet disconnection. 

SWProxy simply refuses to update the IP dynamically. The only thing I can think of is a clean install. At least it would capture in that moment, yes? Perhaps?

**Comment by jake-griffin** [comment]
You aren't supposed to change your phone's IP, and it shouldn't matter at all what the IP address of your phone is. You need to set up a proxy, **not** a static IP, on your phone to tell your phone to point at your computer for access to the internet. If your _computer's_ IP is dynamic, all you should have to do is restart SWProxy when the IP changes to get things working again. When you start it up again, it will tell you what new IP to point your phone at. Again, you don't want to change your phone's IP address to match SWProxy, you just want to set up your phone to point to the IP of your computer using your phone's proxy settings.

**Comment by kakaroto** [comment]
like @jake-griffin said... you need to set up a proxy, not change your phone's IP address. Just search for swproxy or swparser on youtube to see how people set it up.

**Comment by GamingChica** [comment]
Thanks guys. I tried but it wouldn't let me connect to SW. So I thought it
was due to dynamic dns settings. Since you're saying that is not the case,
I must find a way to make it work again.
