### ISSUE TITLE
Mac connection shuts off when setting up proxy on phone

### ISSUE THREAD

**Issue by sougie91** [kakaroto/SWProxy#135]
Probably just user error here, but when I run SWProxy 0.99.2 on Mac OS 10.11.6 and then go to input the static IP/Proxy on my Galaxy S6, my laptop disconnects from the internet and prompts me with "Another device on the network is using your computer’s IP address." Is there a simple way to bypass this?

**Comment by msteudel** [comment]
Are you sure you aren't setting your IP of your phone?

**Comment by sougie91** [comment]
Sleep deprivation gets me again. Only thing I should be changing on phone is the port #, yes? Or also setting a static IP = what SWProxy.py spits out at me? If I do the former, the game gives me an "Error net::ERR_CONNECTION_TIMED_OUT" message when I click "Touch to Start".

**Comment by kakaroto** [comment]
@sougie91 you're completley mistaken on what needs to be done on the phone, you shouldn't set a static IP for your phone, you should set a proxy for the phone to use. 
Here's a video I found (at random) on how it can be done : https://www.youtube.com/watch?v=7GTUQdWg29Q&feature=youtu.be&t=220 @3:40

**Comment by sougie91** [comment]
Thanks for sending this over. Turns out that's what I was doing (despite my unclear description above). But, when I do set things up correctly, nothing gets recorded by swproxy. The game loads fine, but terminal just sits there saying 'Running Proxy server at XX.XX.XX.XXX on port XXXX' when in the past it would download the appropriate info upon loading the game.

**Comment by kakaroto** [comment]
Humm.. well, I was answering mostly about the `"Another device on the network is using your computer’s IP address."` error you would see, that would indicate that your phone's IP address gets set to the Mac IP address, which would cause an IP conflict within the internal network of the router, which causes the laptop to lose its internet connection. I don't think that counts as unclear description.

**Comment by sougie91** [comment]
The issue I have now is the following (copying from anything post): 

After configuring the android phone to use the http proxy, I start up summoners war. It starts up fine. No output appears from swproxy. I can play the game. When I stop swproxy, I can continue to play the game. If I click on the 'event' icon, I get an error indicating that I can't connect to the network. If I then modify the android phone wifi configuration to remove the proxy setting, and I then return to the game, I can click on the event icon and connect to the events http page. So, as far as I can tell, the game is completely bypassing the proxy. 

Any thoughts on this?

**Comment by kakaroto** [comment]
When you open swproxy, what plugins does it list ? could be that it doesn't
find the plugins that actually does all the magic, and a bug could be
preventing the notice from working while allowing the actual game requests
to go through.
You could maybe look at the proxy.log file which should have more
informaiton on what happens.

**Comment by sougie91** [comment]
Plugins: 
- Barion Rune Efficiency Plugin
- SWARFARM Export Plugin
- Generate Runes
- Generate Visit Friend
- Demo Plugin
- Print Unit Collection

Here's the log: [log.docx](https://github.com/kakaroto/SWProxy/files/404194/log.docx)

**Comment by kakaroto** [comment]
ok, so you have the right plugins, and from the log, it seems to be working just fine :
> 2016-08-05 09:33:53,384: proxy - INFO - 192.168.1.75:35424 - POST summonerswar-gb.qpyou.cn:80/api/gateway_c2.php - 200 OK - 51414 bytes

that's the API request with the login, and there's a few API calls afterwards as well. 
Only possibility I guess is if you're using a version of SWProxy that doesn't work... You said you use  0.99.2 and I personally have no idea what's the latest version, or if even the latest release is actually a working version...

**Comment by sougie91** [comment]
I reverted back to the plugins found here (https://github.com/kakaroto/SWProxy) and everything worked fine. Unclear what issue was but glad it's working! Thanks

**Comment by kakaroto** [comment]
Oh ok cool, maybe the plugins were somehow corrupted or something, no idea what the issue was either but i'm glad it's fixed! thanks
