### ISSUE TITLE
[IDEAR] get server direct from Com2Us

### ISSUE THREAD

**Issue by Viper2k4** [kakaroto/SWProxy#137]
I take a look at the calls from SW. And found out there is a relativ early request on:

http://summonerswar-eu.com2us.net/api/location_c2.php
(Other Server on other Contries)

If u call `decrypt_response` on this u got simthing like this:

```
{
   "ip_address":"1.1.1.1",
   "country_code":"DE",
   "country_code_org":"DE",
   "server_url_list":[
      {
         "server_id":1,
         "status":"http:\\summonerswar-gb.qpyou.cn\api\server_status_c2.php",
         "gateway":"http:\\summonerswar-gb.qpyou.cn\api\gateway_c2.php",
         "version":"http:\\summonerswar-gb.qpyou.cn\api\version_info_c2.php"
      },
      {
         "server_id":2,
         "status":"http:\\summonerswar-hub.qpyou.cn\api\server_status_c2.php",
         "gateway":"http:\\summonerswar-hub.qpyou.cn\api\gateway_c2.php",
         "version":"http:\\summonerswar-hub.qpyou.cn\api\version_info_c2.php"
      },
      {
         "server_id":3,
         "status":"http:\\summonerswar-jp.qpyou.cn\api\server_status_c2.php",
         "gateway":"http:\\summonerswar-jp.qpyou.cn\api\gateway_c2.php",
         "version":"http:\\summonerswar-jp.qpyou.cn\api\version_info_c2.php"
      },
      {
         "server_id":4,
         "status":"http:\\summonerswar-cn.com2us.net\api\server_status_c2.php",
         "gateway":"http:\\summonerswar-cn.com2us.net\api\gateway_c2.php",
         "version":"http:\\summonerswar-cn.com2us.net\api\version_info_c2.php"
      },
      {
         "server_id":5,
         "status":"http:\\summonerswar-sea.com2us.net\api\server_status_c2.php",
         "gateway":"http:\\summonerswar-sea.com2us.net\api\gateway_c2.php",
         "version":"http:\\summonerswar-sea.com2us.net\api\version_info_c2.php"
      },
      {
         "server_id":6,
         "status":"http:\\summonerswar-eu.qpyou.cn\api\server_status_c2.php",
         "gateway":"http:\\summonerswar-eu.qpyou.cn\api\gateway_c2.php",
         "version":"http:\\summonerswar-eu.qpyou.cn\api\version_info_c2.php"
      }
   ]
}
```
(i change my IP^^)

So it contains all gatway urls (that what we needed). So now my idear:

- deliver SW-Proxy with this ServerList
- every time a user open SW this list got an update

And now we could filter the request on the exact URL's. This should be bulled proof :)

What u think about?

**Comment by lstern** [comment]
sounds awesome.

**Comment by ruchern** [comment]
@Viper2k4 I accessed one of the sides and it returned me somewhat to be an access token. Can confirm on that?

**Comment by Viper2k4** [comment]
Ignore the Links in the JSON. They respond only well with an valid request. But nevertheless u have to decrypt the value inside swproxy to see the result.

The `location_c2.php` respond without a request. But also, u have to decrypt the respons to get the result i post above.

@all
I could maybe create a PR to get this to work. But i have a question: Where is the best position to store the Server-List? Simply as variable inside the  SWProxy.py? (Python is not my main language^^)

**Comment by Viper2k4** [comment]
https://github.com/kakaroto/SWProxy/pull/146
