### ISSUE TITLE
An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by evangle** [kakaroto/SWProxy#139]
proxy - ERROR - Exception while receiving from connection client <socket._socketobject object at 0x0324A688> with reason error(10054, 'An existing connection was forcibly closed by the remote host')
Traceback (most recent call last):
What does this mean?

**Comment by kakaroto** [comment]
It just means that a connection was closed for one of the sites (most
probably unrelated to summoners war) that your phone was trying to access,
it's kind of 'normal' and no need to worry about it.
