### ISSUE TITLE
Runes without keys

### ISSUE THREAD

**Issue by Starymary** [kakaroto/SWProxy#157]
Hello,

if i visit friends, and i see runes in the file "visit-*.json" they have a key or they have no "key".
with key
.... "runes": {
                    "20": {
                        "occupied_type": 1, 
                        "sell_value": 12750, ....
without key
.... "runes": [
                    {
                        "occupied_type": 1, 
                        "sell_value": 36138, ....
please can you fix it. thx

**Comment by kakaroto** [comment]
I can't fix it, because I don't create that json, that file is returned as is directly from the server. I have no idea why they sometimes do it as a dictionary and sometimes as a list, but SWProxy handles both cases when parsing the json it receives.

**Comment by Starymary** [comment]
thank you for answer.

it is too bad. I have a sql server 2016 and i like it import in this server.
I have problem this line to import if they differend to the other lines. ;)
