### ISSUE TITLE
Download extractable, run SWproxy.exe, black window pops up, then nothing

### ISSUE THREAD

**Issue by Hoodoo66** [kakaroto/SWProxy#168]
Hello,

As the subject states, I run the program and it seems to automatically close itself and nothing launches.  No swproxy.exe found in task manager.  RUN AS ADMINISTRATOR doesn't change anything.  Using Windows 7.  Any ideas?

**Comment by kakaroto** [comment]
Run it from a command prompt to see what the error is

**Comment by Hoodoo66** [comment]
I ran it in command prompt and it magically loaded up properly.  Unfortunately, not on my home network to test it but it appears to have resolved itself!  I'll update with results.

**Comment by kakaroto** [comment]
That's my kind of bug! lol :)
Obviously, if you can reproduce it, then I'd appreciate that output so we can get it fixed. 
Keeping this issue open until you can confirm it all works consistently. Thanks.

**Comment by Hoodoo66** [comment]
Well, it now loads both from windows and cmd prompt so it looks like it resolved itself!  No idea what could have caused it!  Thanks for the reply.

**Comment by kakaroto** [comment]
ok cool! I'll close the issue for now, if it reappears, just reopen the issue or create a new one.
Thanks
