### ISSUE TITLE
Strange results of the extraction with SWParser on W10

### ISSUE THREAD

**Issue by Crownded** [kakaroto/SWProxy#171]
Hi,

I am new with SW Parser but i can't make it work. After reading some topic I haven't found an answer yet.

I manage to extract data from SW but data extracted is not the same for each download. Moreover they do not include monsters and runes.

![image](https://cloud.githubusercontent.com/assets/24824912/21542197/5f92b7de-cdbc-11e6-85df-e5e66b0d2e4f.png)

Comments on the picture : The two blue lines are the results of a first download. The rest are results of a second download done just after.

I'm using W10 and a samsung tablet (android).

Thanks if you can take the time to answer.

**Comment by kakaroto** [comment]
You need to be running SWProxy *then* open Summoners War (if SW was already open, then exit SW and open it again). The monsters and runes data is captured only at the start of the application, before it says "Touch to start".

**Comment by Crownded** [comment]
Yes, for each "download" I spoke about I closed the game (killed the pocessus in the tablet) and opened it again after. I think I did well as some data is captured.

My problem is that after approx. 20 tries the monsters and runes data has never appeared.
