### ISSUE TITLE
Error 10013

### ISSUE THREAD

**Issue by GN009Seraphim** [kakaroto/SWProxy#175]
Hi!

i am really new to this and have heard about rune optimizer and was trying to get the proxy to work but i am getting hte follow message when i try. i've disabled my firewall on my computer and my router before trying and I have also ran program as an "administrator". please help? Thank you!

Error running proxy server : [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions

**Comment by kakaroto** [comment]
According to google : 
https://www.google.ca/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=An+attempt+was+made+to+access+a+socket+in+a+way+forbidden+by+its+access+permissions

```
Please try the following steps:
Restart the windows firewall service.
Reboot the problematic machine.
Restart the “TCP/IP stack”. Run CMD as administrator, type “netsh int ip reset resetlog.txt” to reset TCP/IP.
Try to temporarily disable antivirus.
```

**Comment by GN009Seraphim** [comment]
did not work...this is what i got

C:\WINDOWS\system32>netsh int ip reset resetlog.txt
Resetting Interface, OK!
Resetting Unicast Address, OK!
Resetting Neighbor, OK!
Resetting Path, OK!
Resetting , failed.
Access is denied.

Restart the computer to complete this action.


i restarted like the cmd prompted and still ended with same error 10013

**Comment by kakaroto** [comment]
No idea, sorry, as I never saw that error. 
Did you try disabling the antivirus ? might be an antivirus trying to block it. Or maybe try a different port, with a high number, something like 61234 for example (maximum would be 65535, so anything below that). It might work on that port instead.

**Comment by GN009Seraphim** [comment]
lol omg... you are a genius... seems like just 8080 is blocked...that really high number port works lol

**Comment by kakaroto** [comment]
Awesome! Great to know that fixed it!
