### ISSUE TITLE
No connection possible since Update

### ISSUE THREAD

**Issue by Deniska93** [kakaroto/SWProxy#178]
Hello,

the game can not establish any connection over the proxy since todays update.

Would be nice if you could review that and fix it.

Server: EU

Thanks in advance.

Kowalski93

**Comment by Xzandro** [comment]
That's on your end. I can get the data just fine. (EU)

**Comment by Deniska93** [comment]
Which device do you use?

I tried it with iPhone and iPad. Have no Android device Here with me today.


Am 09.02.2017 um 22:48 schrieb Xzandro <notifications@github.com<mailto:notifications@github.com>>:


That's on your end. I can get the data just fine. (EU)

-

**Comment by Deniska93** [comment]
?Works fine after SW Update tomorrow morning for the Valentines Day event.


Issue can be closed.


Thanks!
