### ISSUE TITLE
New Update Not Working

### ISSUE THREAD

**Issue by FireflyRulesForEver** [kakaroto/SWProxy#187]
Since the new update the SWProxy it will not start.  Can you look into this before the next rune removal day.  Greatly appreciated.

**Comment by kakaroto** [comment]
I tried it yesterday with the latest update and it was working just fine (global server).

**Comment by Neo2SHYAlien** [comment]
For me also working winking without any issue.

**Comment by FireflyRulesForEver** [comment]
I tried a few times but got it to work only when i changed the Port to 6060

**Comment by Neo2SHYAlien** [comment]
It's look like any firewall issue. For me working without any modification on port 8080

**Comment by kakaroto** [comment]
Yeah, it's a firewall issue if it works on 6060 but not 8080. Closing.
