### ISSUE TITLE
Battle result parsing

### ISSUE THREAD

**Issue by nickgronow** [kakaroto/SWProxy#192]
Is there any way to extend this to get the json from the battle results?  I would love to write a little ruby or angular app that takes that data and presents useful statistics on team success rates for dungeons.  Everyone would win from this kind of tracking that is difficult to do right now.

**Comment by kakaroto** [comment]
You can, but not within this app. See the last question of the FAQ (in the README file).
I suggest you check the [SWProxy-plugins](https://github.com/lstern/SWProxy-plugins) repository, it has plenty of plugins and I'm sure you'll find what you're looking for : https://github.com/lstern/SWProxy-plugins/tree/master/plugins

**Comment by nickgronow** [comment]
Nice, thanks so much.  I am going to dive right into this.
