### ISSUE TITLE
Problem with my mac 

### ISSUE THREAD

**Issue by Offlast** [kakaroto/SWProxy#197]
Hi ! I got issues to install SW proxy on my mac. I did all the steps from a tutorial. But I blocked to step 
when I do " sudo Python SW Proxy.py" . I got this result : 
Traceback (most recent call last):
  File "SWProxy.py", line 3, in <module>
    from SWParser.smon_decryptor import decrypt_request, decrypt_response
  File "/Users/thomasdecresson/Desktop/SWProxy-0.100/SWParser/__init__.py", line 1, in <module>
    from parser import *
  File "/Users/thomasdecresson/Desktop/SWProxy-0.100/SWParser/parser.py", line 11, in <module>
    from SWPlugin import SWPlugin
  File "/Users/thomasdecresson/Desktop/SWProxy-0.100/SWPlugin.py", line 1, in <module>
    from yapsy import IPlugin
ImportError: No module named yapsy

Could you help me to solve this ?

**Comment by kakaroto** [comment]
Sorry, I haven't used it in well over a year, I don't even know if it still works or not. Also, I don't have a mac to know how to help you debug it. I'm sure others who tried it before stumbled on this same issue and told others how to get it fixed, maybe you can google for "swparser mac yapsy" and you'll find something.
Good luck.

**Comment by kakaroto** [comment]
So, it looks like there is a working (and much better maintained and packaged) proxy software doing the same thing as SWProxy. You can check it out here: https://github.com/Xzandro/sw-exporter/releases/tag/0.0.24
