### ISSUE TITLE
SWproxy doesn't work

### ISSUE THREAD

**Issue by EvilzGaming** [kakaroto/SWProxy#199]
Usually it shows "Found Summoners War API Request" when i see other people use it on youtube. However when I use it the games loads normally but SWProxy does not show any information when the game loads.

Here are the list of things that I have already tried:

Turn off my antivirus's firewall (AVG)
Uninstalled my antivirus (AVG) along with other files related to AVG. (Reinstalled it later)
Turn off Windows Firewall
Run as administrator
Changed port number from 8080 to other numbers like 8086 etc.
Tried Use Summoners war exporter and faced the exact same difficulty (SWE not showing that it recieved information)
Gave permission to SWproxy to pass through my firewall for both public and private connections in the windows options.

Nothing work please just help me !

**Comment by LarsK-sys** [comment]
Same here :(

**Comment by kakaroto** [comment]
See #198
