### ISSUE TITLE
Build a GUI

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/SWProxy#20]
Eventually, I'd like to have a GUI pop open where you could start/stop the proxy, select the port for the proxy, it would have a status icon (red that turns green after the first request is received) so users know if they configured their phone/network correctly...
I'm sure there's plenty of other stuff that it could do too.

**Comment by ruchern** [comment]
For which OS would you need this for ?

**Comment by kakaroto** [comment]
For all of them of course :) Software always needs to be platform independent :)

**Comment by kakaroto** [comment]
By the way, anyone has any idea on what the UI design should be ? I am really bad at designing UI...

**Comment by Jbag1489** [comment]
I can try building up some kind of mock gui in Swing and just have it not
actually functional yet. Possibly then have a GUI done in Java which would
fix the multi platform issues. Could possibly just run the python script as
well, that could help Mac users.

**Comment by kakaroto** [comment]
No, please no need to mix java with python, it will really just complicate things, this is already a python project, so whatever GUI will be written, it will be in python (so either wxpython or pyQt). I've started to write some gui using pyQt (learning it at the same time), but it's the design that I don't really know what to do with.
So far, I have : a label that says your IP address, a Port: text entry next to it and a Start/Stop button. Using status bar to show debug log from the proxy... no idea what else to put in between.
You can of course build something quick&dirty with Swing just as a mockup, but using MS Paint would do the trick just as well in my opinion :)

**Comment by Jbag1489** [comment]
Ha, ok. I'll see if I can come up with something.

Past design I'm useless in python though :)

**Comment by kakaroto** [comment]
I've push a work-in-progress GUI here : https://github.com/kakaroto/SWParser/tree/gui
Let me know all your feedback!

**Comment by Jbag1489** [comment]
Just (finally) got the GUI to run, however all issues were user related. The GUI is very simple and straight-forward. 

Possible options/additions for future could possibly be remembering the port last used? Not sure the ease of doing that. And also a clear screen button for the log field.

All that being said, it is simple, but I don't think it is a bad thing.

**Comment by ruchern** [comment]
Hmmm, I'm keen to contribute to GUIs, but apparently I'm a .NET Framework developer.

I can help for the Windows one (VB.net/C#.net) on Mac.

**Comment by kakaroto** [comment]
Well, I had never done any QT work before, and in general, I'm not good with writing GUI code. I googled a pyqt tutorial and did it :) You can always help with doing mockups of what the interface should look like.

**Comment by ruchern** [comment]
Is there anyway to not run the GUI on mac?

I have already set up all sorts of alias to run the command immediately from terminal and now I need more keystrokes to start the proxy server.

Just asking only.

**Comment by azrethos** [comment]
@ruchern pass `-g`

**Comment by ruchern** [comment]
@azrethos Thanks!

**Comment by kakaroto** [comment]
or, for the less cryptic, pass `--no-gui` (it's the same thing, but you'll know what it does when you re-read your scripts a month from now :p)

**Comment by lstern** [comment]
What do we need to do to release the GUI ? I tested it and its working fine. My list :

- include icon
- fix log
- include the --no-gui option
- package

**Comment by kakaroto** [comment]
GUI works fine for me if I use py2exe (or on linux), but using pyinstaller causes that issue reported in pull #37, so there's that to fix and whatever else might be needed for the mac.app to work as well.
The parse PCAP option is also not implemented in the GUI, but I don't see it as critical for a release (or maybe it is ? I don't know...)

**Comment by lstern** [comment]
whoever relies on the PCAP parser can use an older version of SWProxy.

**Comment by Jbag1489** [comment]
I had made an icon, I think I out it as an issue? If you want to take a
look and let me know if you like premise of it or any changes I work on some

**Comment by lstern** [comment]
I like your icon. We just need to use it IMO

**Comment by Jbag1489** [comment]
Awesome. I'll get it made into a .ico file. Do you need a jpg/png/bmp or
anything as well?

**Comment by lstern** [comment]
PyQT can work with a png image. I can use the image you posted without problems

**Comment by azrethos** [comment]
looks like this is resolved, lets open a new issue for anything outstanding here
