### ISSUE TITLE
Setup a website for public proxy

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/SWProxy#41]
A lot of people are having issues running the proxy, either because of a router or firewall problem or because they don't have wifi and only have 3G on their phone, etc.. so the best way to make the proxy work for them would be to use a public server for the proxy.
I'm thinking it would be nice to have a server that users can set as the proxy, and when they access it as a web server, it would give them their csv/json files.
Since there's no authentication possible for the proxy, it could either list the files based on IP address (not practical if user wants access from PC and they are on different networks, which is the reason to use this in the first place). Or it could list (in last access order) all captured usernames, and then you can select your username to get the data. Disadvantage is the loss of privacy (you can already visit users, but you can't see their inventory runes)...

In either case, IF such a thing is developed, it would need a big huge DISCLAIMER stating that the user needs to trust 100% the server, because it will capture user information, and could be used to hack/hijack user accounts. And point to the FAQ on how to use/troubleshoot SWProxy locally run, and tell the user that this needs to be a last resort solution to be used only if they trust the server and to use at their own risks, etc...

This is low priority and just an idea, doesn't mean it will get implemented.

**Comment by lstern** [comment]
I had a similar idea a while ago. Setting a proxy so ppl could send summon
/ runs results and create a really big database of drops and summon rates.
I dropped the idea because it relies on someone trusting this server 100%
and while most people don't realize how dangerous an unknown proxy could be
its a service that I would not use. I'm not sure if there's a safe way to
use it. Not sure if its safer to ask people to use the facebook oauth or if
there's some way we can force the game to send the user data after the
login (so the user would turn on the proxy after the game is running)


For the proxy authentication, maybe the person could create the account
using the same device used to access the proxy then login on pc if needed

**Comment by azrethos** [comment]
yea I agree this wouldn't work on the fundamental issue of having to trust the server, even if they setup the proxy after the login (PITA) what if the game restarts and auto logs them in? it's a can of worms and liability, i think our focus should be providing the users something safe and easy to run locally; if we give them a good method and they can't figure that out how then do we expect them to figure anything else in the rune export/import pipeline?

**Comment by Jbag1489** [comment]
I think while this is in theory a good idea, I see lots of practical
issues.

It is a little more difficult,  but if I'm not able to run the proxy I'll
still just capture my pcap with tPacketCapture.

I know not the solution being discussed, and also the whole packet capture
was an issue for people.

**Comment by kakaroto** [comment]
Well, it's a litlte more than that. from my understanding the 'session key' can be used to do anything in game and it *never* (?) expires so even if the login info is not there, it's still dangerous, ALSO, the proxy acts for the whole device, not just for SW, so anything you browse to can be intercepted, and if you don't use HTTPS, any other logins/websites will get captured.
So you definitely need to trust the server 100%. Having this huge database is great, BUT, I don't think people would use it. This would only be used as a last resort if someone needs to on FRR day and they've just spent 3 hours trying to get the proxy to work and it didn't, but I don't think people will use the public proxy just to help get a bigger database of runs/drops.

As for packet capture, it can be blocked maybe by SW in the future, or used to ban people, also, the idea came actually from someone who was on iOS and who was trying to capture using tcpdump in a terminal emulator on his phone, and the pcap was not working for him for some reason, and he couldn't use the proxy because he only had 3G capabilities and no wifi, etc..
