### ISSUE TITLE
Find IDs for Water/Fire/Wind Scrolls

### ISSUE THREAD

**Issue by dotneB** [kakaroto/SWProxy#43]
Find and confirm the id of Water/Fire/Wind Scrolls and add them to inventory_map in plugins/GenerateRunes.py. Right now our best guess is that they're 4,5,6 but we're unsure of the order

**Comment by porksmash** [comment]
I can confirm that a fire scroll is ID 5. If I had to guess the other two I'd go by the usual Water/Fire/Wind order Com2US uses (see monster IDs) that would make water == 4 and wind == 6.

**Comment by dotneB** [comment]
Just got a Wind Scroll for world boss (in a F treasure box of all thing :D) and can confirm that the ID for Wind is as @porksmash predicted. I purchased at Water Scroll with glory points to confirm it's ID as well.
