### ISSUE TITLE
Grindstone/Enchant inventory data

### ISSUE THREAD

**Issue by dozens** [kakaroto/SWProxy#45]
Is the data for unused grindstones & enchant gems buries somewhere (it must be)? I would be nice if this data could be packaged up and added to the optimizer file so it could at least list in a tab similar to the "adv rune" tab.

**Comment by dozens** [comment]
found it in the "login" data:

crafts = data['rune_craft_item_list']
rcType = item['craft_type']
rcSet = item['craft_type'][:-4]
rcStat = item['craft_type'][-4:-2]
rcGrade = item['craft_type'][-1:]

**Comment by lstern** [comment]
thanks!

**Comment by lstern** [comment]
I've implemented this on my fork and also included this info on _optimizer,json and @Xzandro is already using it.  Should we include grindstones in runes.csv file or create a new file ? Also, we need a table of grindstones values per grade.

**Comment by Xzandro** [comment]
About the grindstone and enchanted gems values: i was looking for it, too. Here are useful information: http://summonerswar.wikia.com/wiki/Enchanted_Gem http://summonerswar.wikia.com/wiki/Grindstone . The question is: is that even needed for the SWProxy to handle?

**Comment by lstern** [comment]
#52

**Comment by lstern** [comment]
summoning @porksmash

**Comment by lstern** [comment]
@kakaroto, @Xzandro asked us to include grindstones support on next release. He already tested the code with his optimizer and also with the web version.

**Comment by porksmash** [comment]
I would like to implement this on swarfarm as well! I'll put in a pull request soon to update the _swarfarm.json

**Comment by kakaroto** [comment]
Just gonna drop this here: https://www.reddit.com/r/summonerswar/comments/4cbhh9/help_us_find_some_missing_numbers_for_enchanted/

**Comment by lstern** [comment]
are we exporting the grindstones/enchants as a separate csv ?

**Comment by Xzandro** [comment]
That's what i got so far. http://pastebin.com/E8tCkLc3 HP flat Legend still missing.
