### ISSUE TITLE
some people are getting wrong ip after this update

### ISSUE THREAD

**Issue by lstern** [kakaroto/SWProxy#48]
"First thing I noticed was that the IP on the cmd seemed to be using my local IP, whereas on the GUI version it was using a non local IP."
https://www.reddit.com/r/summonerswar/comments/490u23/swproxy_new_version_released/d0odyvb

I traced this relevant code change back to ffa2ff11c760784624d36cd97b1073804e8440cd

some interesting report :
". I have little observation, my pc have several network devices (virtual box, vpn, wifi, ethernet) and the app is not taking by default the wifi IP you should put to ignore 169.X.X.X IP following the standards of IP range i doubt most of ppl use those numbers"
https://www.reddit.com/r/summonerswar/comments/490u23/swproxy_new_version_released/d0ofux2

**Comment by cgurnik** [comment]
c4df8f1 broke for me :(

```
Traceback (most recent call last):
  File "SWProxy.py", line 203, in <module>
    start_proxy_server(options)
  File "SWProxy.py", line 166, in start_proxy_server
    my_ip = get_external_ip()
  File "SWProxy.py", line 113, in get_external_ip
    ordered_list = sorted(socket.gethostbyname_ex(socket.gethostname())[2], key=priority)
  File "SWProxy.py", line 103, in priority
    if address_in_network(ip, "192.168.1.0", 24):
  File "SWProxy.py", line 97, in address_in_network
    address = dotted_quad_to_num(ip)
  File "SWProxy.py", line 89, in dotted_quad_to_num
    return struct.unpack('L',socket.inet_aton(ip))[0]
struct.error: unpack requires a string argument of length 8
```

**Comment by lstern** [comment]
@cgurnik IPV6 ?

**Comment by lstern** [comment]
fixed problem for the original reporter https://www.reddit.com/r/summonerswar/comments/490u23/swproxy_new_version_released/d0om2ec
