### ISSUE TITLE
After patch 2.0.7 proxy no longer captures data

### ISSUE THREAD

**Issue by dANIel1989l** [kakaroto/SWProxy#49]
https://www.reddit.com/r/summonerswar/comments/4as3aa/did_anyone_elses_parser_proxy_stop_working_when/

I tested it and get nothing, maybe they changed the encryption key?
Edit: Checked the proxy.log and it is transmitting the data ok, just not processing it

**Comment by dozens** [comment]
Traceback (most recent call last):
  File "SWProxy.py", line 36, in onResponse
    req_json = json.loads(req_plain)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")

**Comment by JasonGoemaat** [comment]
I have the issue too, but I get this error:

    unknown exception: Error -3 while decompressing data: incorrect header check

**Comment by JasonGoemaat** [comment]
Seems the decrypted request might not be 100% correct:

`onRequest
decrypting request:
AFN58QQVs382rxauma0sxl5sbzP6KVUJAeHV7nAJMVXWsY/nDpLG51kqDQnVJnc2knnNzlO7kLFv6kBJxxCzYxJEh17yYr9VoibhWQwfSNCKuQvSxcSppckves/qRnJTDa7xNZMKcNwtfPCj2zIUfqMrbr26wEakTGVc9gbEzN/1HnGrYg/qqAIK7Lmzzz9AdayfqpOMeASRy6gzCXAYqoTL4ZexpCA3AqFgjXS03IOWo/O8u/i5UB7ZcFau2oSBlyrsXC/5WZ+B6WqTcaI10I69nu0e7sz9s3KvKoVBN8IiyYa2qXv0SlYShKTDUGi7CW2DErl0mDg7d+LXKxmzQKysoxWpwbrxbJb+1mAR+R2N1aGv7A/p+yd9Oqi/w75m2Cc1X0W8sBnrFY6pHavj34bSfOOU78xPB0ahc2Xgag4=

decrypted request
18:√ΩpwZ╝Θ║┘Çæ♀▌▓ #S╧╗▼√9╩ÉI
yIû∙╣?æ?        Ä♦▌₧╡KX╤~z∟■ß◄a∙)Ω╚o∟╕w╬q3≥∞ü0>∩_‼╡,rn╬ÿ╬ü      ╡[

request json exception

decrypting response

K/rtEQaBlNDewP3fLcY3cnqxDqJyHyUqUAa/LnlzDD/4nEke9pZQ1vDg3kXEZ7vKjIrmAmI5CfjTqpws6zVtasOtenPrOEWy2aFcDHrF08cKIMDAxwj21OWO2mQPUC+1NVIVhxm0xs+56es9wNYikpPanu1IOo9ALS3EwP7GYzhZkA01ijWtC2JkcVyu9jVD77Z1z747TGIOFpUte8D6/P6ni8OKe1An+ssmVxz7xlUExW9Lp6bzV3cJ6Pn82bjfXzFq4wJaZKxYIJ4Cmf9xab7v8mOz6YpMUvEfzTYcLMXiJQOQAULgdR26o7KfbmLcr5KX9jm6s9Ld6XUU3W8cabvvgNVnoyPLFqo74/qHvqQ6VAXwgd7ntEN9Nax2c8je8Q/J/cuJO84WY2ZesOoTl1KQJscMDRGkaTRogZ12oomTgivAL2eafqtjix6l5uMxded4ANQuOfut5IV8rkpwPtdMY/0o11nZ3RJQ9YTeZC6HFZSD3azqbqM5Av45dw0M6Au/g5QccUTbzor12uxBFnKvEsIJP+s49cM1oOcs0xB26EQvHHsw9F0/YOrITiphNiEYQpA80TMlQQH4fpjr6G3k5t62+/y8Y+mzvlAv7wbN3g2q/nJS/p+frMjef0VyRFJDWDydq1f4yAcnZxsirAiO7Rs63VbmEDCl7cilztdI5G9BYQWq83vxle0Njzm7800nBwkLAchuuBSKekBZL9pxo8mdoECLp8HMpLTaCMszPfUF8bvfnr1DvfgucULk4OIXdT36nfkyZOcQQFgb78u40Ql/wO40rWUGT5+HHcLSrNiU2ZKBLQmBdH4m7T+IL/7GNdx41GWHws5corLduU3ZGiPcS1OgJQfv/8cVhkNMyGhcyZi8fNcLX0zIcDTRI75jTbmCWOYkOYqtDJ8N/fueZC8rT5kOPkayNYEKb94=

unknown exception: Error -3 while decompressing data: incorrect header check`

**Comment by dozens** [comment]
I happen to have some old captures and prior to the update the json was in text and now it looks like it is binary (probably encrypted).

**Comment by PhilPhil404** [comment]
Same problem. It doesn't capture anymore.

**Comment by Fireheade257** [comment]
Yeah it's not capturing any info for me either. Login is fine, but it doesn't capture any data.

**Comment by Fireheade257** [comment]
2016-03-19 10:49:26,875: proxy - INFO - 192.168.1.82:33732 - CONNECT live.chartboost.com:443
2016-03-19 10:49:26,877: proxy - ERROR - Exception while receiving from connection client <socket._socketobject object at 0x02C81A40> with reason error(10054, 'An existing connection was forcibly closed by the remote host')
Traceback (most recent call last):
  File "proxy.py", line 266, in recv
error: [Errno 10054] An existing connection was forcibly closed by the remote host
2016-03-19 10:49:26,878: proxy - INFO - 192.168.1.82:49678 - CONNECT image-glb.qpyou.cn:443

**Comment by azrethos** [comment]
They changed the encryption key @kakaroto, @everyone.

We will have to mine the new key before this project can work again

**Comment by Toosick** [comment]
Any word on this?

**Comment by Xzandro** [comment]
Still waiting for kakaroto, I guess. :(

**Comment by lstern** [comment]
Yes. I don't have the knowledge to get the new crypto key but I'll give
another try by the weekend. Sorry for the inconvenience.

**Comment by knifesk** [comment]
Always the same with Goku.. he is always around when there is food.. now, that the world needs him, it's probably dead.

**Comment by asmodeus78** [comment]
I hope it resolves I had just discovered the existence of this fantastic tool

**Comment by djluis48** [comment]
I would love to use ths tool again. Its so awesome.

**Comment by fukni** [comment]
Counting down, 10days to next FRR. Hope this can be fixed, I don't mind it becomes a paid programme.

**Comment by olympicboxer** [comment]
crossing my fingers here. i dont mind paying for this program either. great work and the best tool ever for sw

**Comment by aeonshawn** [comment]
I agree. More than willing to pay for the tool. Where's the donate button? lol.

**Comment by azrethos** [comment]
@kakaroto has a donate link here that he posted on reddit some time ago:

https://paypal.me/KaKaRoTo

he would be the one directly responsible for the work needed to fix the tool (sniff new key)

**Comment by aeonshawn** [comment]
thanks. maybe a donation will grab his attention. haha.

**Comment by Tigasmigas** [comment]
Paid to use you just will open a war with com2us and with all the reason :) . So donate yes , paid app no... dont get greedy .

**Comment by lstern** [comment]
app will remain free and open source (except  the crypto key).

**Comment by daddyrubin** [comment]
Hope this is able to be updated. I resorted to manually entering my stuff into the optimizer. Had to start now to be ready for FRR. This is an awesome tool. I will definitely donate when my financial situation improves.

**Comment by leprov** [comment]
I've checked the code yesterday with @lstern , the key seems to be unchanged, we have to deep digger to see what has actually been modified. I'll probably try to go further tomorrow

**Comment by azrethos** [comment]
@leprov how did you do this? did you try to decompile the key, change a few characters and observe the same mangled results/exception? (same results would imply key is bad). I'm curious because I can help. I'd need your debugging notes tho

**Comment by azrethos** [comment]
@leprov how have you tested it? I can help but I'd need your notes, perhaps we could start a Slack?

**Comment by leprov** [comment]
@azrethos I reversed the game code and compared the key generation algorithm between parser and sw code. Same code, and probably same result. I didn't check furthermore, I need more tools for it, but I have some ideas about what I need to do next. How can we communicate on this? I'm already in touch with @lstern through "Line" messenger

**Comment by omikronsc** [comment]
Isn't it that they set AES IV to first 16 bytes of key but you are using zeros instead?

**Comment by leprov** [comment]
@omikronsc  In current implementation, AES IV is indeed all 0s. Where did you find the IV is set to the first 16 bytes of the key? is it an assumption or did you find it in the code?

**Comment by omikronsc** [comment]
Indeed I checked EncryptManager.

**Comment by leprov** [comment]
Things are not done in the JAVA, they are done in the C++ that's called from the JAVA.

**Comment by omikronsc** [comment]
I'd like to help, however to speed things up I'd like to ask some questions. I don't think here is a good place for them.

**Comment by leprov** [comment]
I'm talking through "line" messenger with lstern, add me there (ID = leprov)

**Comment by kakaroto** [comment]
Hey there everyone!
I just got back from vacation yesterday night! I've got about 451 new emails to check, but I saw this in passing when I was abroad, so I'll get to it once I have some free time.. I've got a lot of catching up to do right now!

**Comment by vehumet** [comment]
As @leprov said, our target is in the compiled, truncated, and of course
obfuscated shared object file.
That's all I know for me now, and cannot move on for lack of skill in
reversing :(

**Comment by edroot** [comment]
Kakaroto Мы верим в тебя старый самурай

**Comment by olympicboxer** [comment]
good luck to everyone trying hard to make this a thing again ! your efforts are genuienely appreciated

**Comment by kakaroto** [comment]
Enjoy!

**Comment by Xzandro** [comment]
Thanks man for your hard work! You saved my motivation to play the game and develop on the optimizer. Can't thank you enough.

**Comment by knifesk** [comment]
You're awesome!

**Comment by Tigasmigas** [comment]
Yea please...... i dont know what to do with the fix you put there :(

**Comment by Fm90** [comment]
I don't know eaither how to build the SWProxy.py... I get error line 85 lel xD im totaly newbie... Please make a realase build thanks or/and teach us how to do it :D

**Comment by olympicboxer** [comment]
A big thank you from all of us to you

**Comment by daddyrubin** [comment]
Thanks for working on this. How can I get it to work on Windows though? I am still not able to get it to run.

**Comment by Royushken** [comment]
I am also confused as to how to get this working now on windows. I downloaded version .99 but there doesn't seem to be anything executable. Thanks!

**Comment by Xzandro** [comment]
Guys, just be patient. I'm sure there will be a new release soon. :) Be happy that SWProy will work again. :D

**Comment by dANIel1989l** [comment]
They have fixed the source files but haven't recompiled the .exe's yet. You can run it from the console if you have python and all the required libraries installed. Instructions have already been provided for linux and mac in the readme, windows is possible but a bit harder. They should have it ready to go soon, just have to be patient :)

**Comment by Royushken** [comment]
Ohh gotcha. I just wanted to make sure I wasn't missing something. This site and coding are all foreign to me, so I thought maybe I just couldn't figure it out. Thanks.

**Comment by daddyrubin** [comment]
That was my thought.  Like Royushken said, i just wanted to make sure i wasnt missing something.  It is definitely nice to know that it is being worked on.

**Comment by hotdog69** [comment]
Haha i thought it was already fixed and panicked when i couldn't get it to work, again! Hoping for a speedy fix and i'll admit that I'm far too reliant on this..

**Comment by leprov** [comment]
It IS fixed, there is just a bit more work before releasing the new binaries. The ticket is closed, so it's ok, just wait a few more hours ;)

**Comment by kakaroto** [comment]
Not necessarily a few hours, I did make a 0.99 tag/release but I didn't bother (and I'm too tired today) to do an upload of binaries. Maybe some of the other contributors can take care of that (I know there was some work on using pyinstaller, I'm not sure if that's the preferred method now or whatever).

**Comment by lstern** [comment]
I can do it if someone build the mac package for me.
