### ISSUE TITLE
Not gathering data

### ISSUE THREAD

**Issue by hotdog69** [kakaroto/SWProxy#58]
When I run SWproxy.py i get this, and when i open my SW the data doesnt gathers.

Admins-iMac-2:~ admin$ /Users/admin/Downloads/SWProxy-0.99.1/SWProxy.py ; exit;
########################################
# SWParser v0.99 - Summoners War Proxy # 
########################################
	Written by:
		KaKaRoTo

	Authors:

	Plugins:

Licensed under LGPLv3 and available at: 
	https://github.com/kakaroto/SWProxy

**# ## Failed to load GUI dependencies. Switching to CLI mode**
Running Proxy server at 192.xxx.x.x on port 8080

**Comment by Bmoreatl** [comment]
SAME

**Comment by Bmoreatl** [comment]
Solved: Looked in FAQ about phone not booting. Cut wifi off. Start SW when it gets to Bringing in Friends of load screen cut WIFI on and make sure your IP and port settings are correct then switch back over to SW and let it load,

**Comment by hotdog69** [comment]
I am able to enter SW but the data does not gather on the terminal during the loading screen in game

**Comment by kakaroto** [comment]
looks to me like it's not listing any plugins, since data gathering is done by the plugins, that's why it's not gathering anything. I'm guessing the mac build was not done/tested properly. I'm not sure who did it, but I'll poke @stanleykylee in case he can help.

**Comment by stanleykylee** [comment]
The build in the release has been tested on several different macbooks and are working fine. The initial release did not include the plugins but the subsequent release labeled SWProxy-mac-2.zip includes the plugins.

That aside, @hotdog69 , are you using the extracted binary from SWProxy-mac-2.zip? Your initial message shows you running SWProxy.py - a python file. Are you compiling the code yourself?

**Comment by hotdog69** [comment]
I ran extracted binary from SWProxy-mac-2.zip on my imac which has the latest OS and still it came up with "/Users/admin/Desktop/SWProxy-mac-2/RunSWProxy.command: line 2:  1979 Illegal instruction: 4  `pwd`/SWProxy"

I switched over to my macbook which has OS 10.9 and did the same thing and it worked. IDK whats up with my imac, but at least i finally got it to work. Guess im fine with this. Thanks!

**Comment by stanleykylee** [comment]
Thanks for the update! This makes it even more puzzling. @kakaroto @lstern We can close this one for now and I'll investigate the illegal instruction in the other open issues.
