### ISSUE TITLE
Uninstall previous version?

### ISSUE THREAD

**Issue by desert-jay** [kakaroto/SWProxy#60]
Do I need to uninstall the previous version of the SWProxy? 

Do I then follow the same steps as before for installing this new version or did something change? It seems that there are a few differences in starting it up so I wanted to check. 

I tried following the steps show, but it keeps telling me "No such file or directory" so I'm not sure what I have done wrong.

**Comment by stanleykylee** [comment]
None of the SWProxy versions actually install anything. They are self containing executables that will run from where they reside.

Which version are you using (Win or Mac) and which steps are you referring to?

**Comment by desert-jay** [comment]
I have Mac OS X 10.11. I was using the version of SWProxy just  before the 2.07 update that caused the errors.

**Comment by stanleykylee** [comment]
So you've downloaded the latest release (https://github.com/kakaroto/SWProxy/releases/download/0.99.1/SWProxy-mac-2.zip) and have it extracted?

Then you've run the .command file?

Could you send a screenshot of what you mean by the "No such file or directory"?

**Comment by desert-jay** [comment]
I will as soon I get home. I'm out of town on business so I will touch base later this week. 

Thank you for your assistance.

**Comment by desert-jay** [comment]
I just re-downloaded the file and it works like a dream. Thank you for your assistance.
