### ISSUE TITLE
[Ubuntu]version 0.99.1 - wrong ip adress 

### ISSUE THREAD

**Issue by cwgmacedo** [kakaroto/SWProxy#64]
Swproxy gets the wrong ip adress on ubuntu, on GUI and non GUI version

![captura de tela de 2016-03-28 14-52-41](https://cloud.githubusercontent.com/assets/4204173/14085237/1291e234-f4f5-11e5-98d1-d7e02c0da645.png)

########################################
# SWParser v0.99 - Summoners War Proxy # 
########################################
	...

Running Proxy server at 0.0.74.79 on port 8080

**Comment by azrethos** [comment]
here's my best guess for a way to fix this, it works for OSX, but requires netifaces module

ip =  ip4_addresses()[0]

```
from netifaces import interfaces, ifaddresses, AF_INET

def ip4_addresses():
    ip_list = []
    for interface in interfaces():
        try:
            for link in ifaddresses(interface)[AF_INET]:
                ip_list.append(link['addr'])
        except KeyError:
            continue
    if '127.0.0.1' in ip_list:
        ip_list.remove('127.0.0.1')
    return ip_list
    
    
# returns a list, first address is likely the correct one
print ip4_addresses()
```

**Comment by lstern** [comment]
not sure if we will have the same problem. Maybe we can allow user to
select the correct ip (dropbox for gui , list all valid ips on console)

**Comment by azrethos** [comment]
we could implement a flag really quick (--ipguess2) or something to enable the above code (instead of current ip detection); then we could ask users to run it with this flag and see if the first ip works out of the box, we'd need to test linux and windows certainly.

This seems like the best xplatform code, I do like your idea of the dropdown (maybe GUI-less just picks the first one)

**Comment by lstern** [comment]
]relevant info](https://www.reddit.com/r/summonerswar/comments/4camql/swproxy_linux_returning_loopback_ip/d1gobu9?context=3) "You comment made me double check. It's not trying to use 127.0.0.1 which is blocked in the code, It's trying to open the proxy on 127.0.1.1
no clue where its getting that address from. Loopback is 127.0.0.1"

**Comment by kakaroto** [comment]
This is being discussed in https://github.com/kakaroto/SWProxy/pull/38 and it's been fixed already, so expect it to work on the next release.

**Comment by kakaroto** [comment]
FYI: when I tried the app during FRR day, it gave me 127.0.0.1 (weird since 127.* should be filtered out), so I updated my local git and then it worked properly.
