### ISSUE TITLE
Extend the plugin-system to allow csv to be saved on different formats

### ISSUE THREAD

**Issue by lstern** [kakaroto/SWProxy#71]
We need a extra method the plugin system so we would be able integrate sw proxy with tools like google spreadsheet or the Rune Opitimizer

**Comment by ruchern** [comment]
@marin-k-marinov doesn't seem to be active on his/her Rune Optimizer updates. We probably need someone to start a new project based on the files uploaded here: https://github.com/marin-k-marinov/swrunes

I'm keen to assist with this.

**Comment by stanleykylee** [comment]
is that the repo for http://swrunes.all.my/?

**Comment by Xzandro** [comment]
I am very active, but only the Win 10 app though.

**Comment by lstern** [comment]
managed to  archive that using the existing code

**Comment by lstern** [comment]
https://github.com/lstern/SWProxy-plugins/blob/master/plugins/GoogleSheetWriter.py

**Comment by ruchern** [comment]
@stanleykylee Yes that is the repo for swrunes.all.my

**Comment by marin-k-marinov** [comment]
Hi guys, I dont have time to update the repo. You can find the latest code from the Offline version 1,06 from http://swrunes.all.my/
