### ISSUE TITLE
IP adress wrong?

### ISSUE THREAD

**Issue by Phreak1202** [kakaroto/SWProxy#72]
on the new version 0.99.1 i cant download my awdata anymore, and i didnt change anything... last time i used version 0.97 which functioned perfectly and this version does nothing the only differents between them is their IP Adress, so can this be the problem?
(i have tried all solutions to solve the problem which you have wrote into the info)

![version99](https://cloud.githubusercontent.com/assets/10314332/14206469/9e52aa30-f813-11e5-9452-35c71c8d9f2f.png
here it doesnt work

![version97](https://cloud.githubusercontent.com/assets/10314332/14206470/9fdac158-f813-11e5-8b85-d1958e35d98d.png)
here it worked before patch XXXXX of summonerswar

**Comment by kakaroto** [comment]
This is being discussed in https://github.com/kakaroto/SWProxy/pull/38 and it's been fixed already, so expect it to work on the next release.
