### ISSUE TITLE
Nothing logged, but proxy working

### ISSUE THREAD

**Issue by qdeeds76** [kakaroto/SWProxy#75]
Heya.  I have been unable to get a log for a while now.  I run swproxy.exe, get the phone connected to the proxy, but it makes no proxy.log or any of the various log files for the optimzer or swarfarm.  I know the proxy is working at the correct port, because I cannot load any web pages as soon as I turn off the proxy.  I am perplexed as to why I am not getting a proxy.log or anything.  I do have it unzipped to c:\SWProxy as I had heard that is where it works by default.  Anyone have any ideas?

**Comment by softbearlolz** [comment]
cum2us changed code ,so old version cant grab data.

**Comment by qdeeds76** [comment]
Hi I seemingly found the answer.  I had been very careful to always run swproxy.exe as an administrator, but the moment I forget it worked.  So I know I can't offer much of a technical angle on my issue, but hopefully that can help someone else having a similar issue.
