### ISSUE TITLE
Guild Attack List

### ISSUE THREAD

**Issue by Anacondych** [kakaroto/SWProxy#76]
As guildmaster i would like monitoring attacks of my guildmates. 

Please make detailed List of Attacks from Guild Battle Log with next breakdown:
OppGuild_name, Guildmate_name, Oppguildmate_name, win/loss, Guildpoints_acquired, Max_guildpoints_from_GuildBattle.
 
Thanks

**Comment by dANIel1989l** [comment]
This belongs in the plugins repository and is already a planned feature, we'll get around to it.
https://github.com/lstern/SWProxy-plugins/issues/23
