### ISSUE TITLE
Update 2.1.0 broke proxy again

### ISSUE THREAD

**Issue by knifesk** [kakaroto/SWProxy#82]
Hello.. as the title states.. they have made some changes on the login process that makes the game to stop if you're using the proxy.. Don't know what, because if you start the game, login, and then change the proxy settings on your phone the requests gets detected by the proxy.. but if you close the game and open it again it will stay after the "reading data files" with the spinner animation only and nothing happens... Maybe they have changed the login system to be TCP or UDP based and the rest of the game stills HTTP?

**Comment by knifesk** [comment]
If you double tap the home screen right BEFORE the "Connecting to game server" message appears and then switch to settings and set the proxy up, everything works as excpected..

**Comment by dANIel1989l** [comment]
What phone, pc, etc are you using? It still works same as usual for me.

**Comment by knifesk** [comment]
iPhone 6s iOS 9.3.1 (non jailbroken), I've downloaded the latest version of the game not 10 minutes ago... My pc is Windows 10, with static IP and no FW... Already tried with my alt account, and rebooting the PC...

**Comment by kakaroto** [comment]
That behavior has been there since day 1, it happens sometimes for some people, sometimes it doesn't happen, nobody knows why.

**Comment by knifesk** [comment]
Oh, good to know.. I'll try from other phone/rebooting my phone

**Comment by Jamaisme** [comment]
This is happening to me as well... Across different devices (all apple though) / across IPs. Must be flagged by account or ios only.. so weird?  Is there another spot past the login screen where this info could be grabbed?

**Comment by azrethos** [comment]
was not working for me, iOS, have not tested android

**Comment by porksmash** [comment]
Android working for me

**Comment by Toosick** [comment]
This used to work for me but after the update it is doing exactly what OP said.

**Comment by HardcoreHostile** [comment]
I believe this issue: https://github.com/kakaroto/SWProxy/issues/83 covers this, it has broken for me too since the last update.
