### ISSUE TITLE
Trying to run SWParser with a pcap file from wireshark.

### ISSUE THREAD

**Issue by QuillyT** [kakaroto/SWProxy#84]
Since SWProxy seems to be having some issues at the moment, I used Charles and Wireshark to grab a pcap file and I'm trying to put it through the decryption routine (Skroll did this successfully in #83).

I'm trying this in the SWProxy project folder:
```
> python SWParser.py myPCAPfile.pcap
```

But I'm getting this error:
```
Traceback (most recent call last):
  File "SWParser.py", line 3, in <module>
    from SWParser import parse_login_data, parse_visit_data
ImportError: cannot import name parse_login_data
```

Am I doing something wrong or is this because SWParser is no longer meant to be run by itself?

**Comment by kakaroto** [comment]
Yeah, SWParser is not meant to be run by itself anymore, that's why it doesn't work. 
Keeping the issue open until the feature is brought back.

**Comment by lstern** [comment]
SWParser is not maintained. Try to upload the pcap file to swarfarm

**Comment by QuillyT** [comment]
Oh wow, I didn't Swarfarm would do that.
I just did it and it worked perfectly. 
Thanks for the suggestion!

BTW thanks guys! It's really cool that you have put your time into this and shared it with us.

**Comment by kakaroto** [comment]
ha, yes, I forgot that swarfarm supports pcap import. sorry!

**Comment by mockfake** [comment]
So I was using locally grabbed pcap files, SWParser and a copy of the SW Rune optimizer running locally and bypass Swarfarm entirely.  Any chance SWParser will be resurrected in the future?  My phone doesn't seem to like SWProxy -- older version of IOS, I suspect, but haven't investigated fully.
