### ISSUE TITLE
SwProxy not working mac/ios

### ISSUE THREAD

**Issue by geeyummy** [kakaroto/SWProxy#85]
I have a mac/ios and when I open the swproxy and do everything, the game doesn't load and the info doesnt download to swproxy. Not sure what I'm doing wrong as I followed every step from tutorials.

**Comment by kupoback** [comment]
See #83

**Comment by geeyummy** [comment]
I tried, still not working.

**Comment by deftera** [comment]
I'm having the exact same issue. Looks like it's a known issue though. 

I tried the "double tap the screen" while it's loading trick and have had 0 luck with that method as well.

**Comment by ruchern** [comment]
I am not having the problem on Mac OS X.

**Comment by pocketq10** [comment]
i am also having the same issue. they updated from the2.0.5 version to 2.1.1 idk if it has anything to do with that.

**Comment by cvbarros** [comment]
Same issue here.

**Comment by lstern** [comment]
same as #83
