### ISSUE TITLE
issue connection to proxy server

### ISSUE THREAD

**Issue by pocketq10** [kakaroto/SWProxy#88]
i use the sw proxy a month ago and worked fine, now idk why i cant connect to it anymore. any suggestions?

**Comment by Levriette** [comment]
Same issue here ....2 weeks ago the proxy worked but today I cannot pass the loggin step.

**Comment by msteudel** [comment]
Have you guys tried changing the proxy settings right when it says downloading?
https://github.com/kakaroto/SWProxy#i-can-use-the-internet-with-the-proxy-but-i-cant-start-the-game

**Comment by Levriette** [comment]
Yes I tried that.
But I used an Ipad. Is it related to an IOS bug with the proxy ?

**Comment by lstern** [comment]
same as #83
