### ISSUE TITLE
Syntax error when running SWProxy on Mac

### ISSUE THREAD

**Issue by sougie91** [kakaroto/SWProxy#91]
Running `python SWProxy ` returns 
```
File "SWProxy", line 1
SyntaxError: Non-ASCII character '\xcf' in file SWProxy on line 1, but no encoding declared; 
see http://python.org/dev/peps/pep-0263/ for details
```
Thoughts?

**Comment by msteudel** [comment]
This might be helpful for devs: http://stackoverflow.com/questions/10589620/syntaxerror-non-ascii-character-xa3-in-file-when-function-returns-%C2%A3

**Comment by msteudel** [comment]
Also @sougie91 it might be helpful for them to have your operating system type and version.

**Comment by aureus1** [comment]
@sougie91 Are you trying to run the osx binary (the 15MB file) with python?  if you're using python directly, you want to grab the source (via git or zip download) and run:
`python SWProxy.py`

The `SWProxy` file is an executable - just double click it to run.

**Comment by kakaroto** [comment]
Considering it says `File "SWProxy", line 1`, not SWProxy.py, I'm going to guess he tried to run the executable itself. Feel free to re-open the issue if that's not the case.
